export const ERR_INVALID_METHOD: any;
export const ERR_HEAD_SET: any;
export const ERR_ADDRINUSE: any;
export const ERR_UPGRADE: any;
export const ERR_STREAM_DESTROYED: any;
export const ERR_UWS_APP_NOT_FOUND: any;
export const ERR_ENOTFOUND: any;
export const ERR_SOCKET_BAD_PORT: any;
export const ERR_SERVER_DESTROYED: any;
